  worker:
    build:
      context: ..
      dockerfile: docker/images/api.Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A app.workers.celery_app worker
    depends_on:
      - redis

  celery-beat:
    build:
      context: ..
      dockerfile: docker/images/api.Dockerfile
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A app.workers.celery_app beat
    depends_on:
      - redis
