"""add_title_and_description_to_investigation_events

Revision ID: 73131b121b0b
Revises: 8f3b4567c890
Create Date: 2026-08-23 14:31:02.332238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73131b121b0b'
down_revision: Union[str, None] = '8f3b4567c890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE (post-audit fix): the autogenerated version of this migration
    # retyped alert_embeddings.id/tenant_id/alert_id from UUID to VARCHAR
    # (mirroring an incorrect ORM declaration) and dropped/recreated its
    # foreign keys. That cannot execute: PostgreSQL rejects ALTER COLUMN
    # tenant_id TYPE VARCHAR while an FK to tenants(id) still exists, and
    # uuid->varchar would orphan tenant isolation anyway. The ORM model was
    # corrected to UUID keys instead; only safe index/constraint alignment
    # remains here. The embedding dimension change was moved to
    # b8d2f5a1c4e7 which handles mismatched vectors explicitly.
    op.drop_constraint(op.f('alert_embeddings_alert_id_key'), 'alert_embeddings', type_='unique')
    op.create_index(op.f('ix_alert_embeddings_alert_id'), 'alert_embeddings', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_embeddings_tenant_id'), 'alert_embeddings', ['tenant_id'], unique=False)
    op.drop_column('alert_embeddings', 'text_source')
    op.drop_column('alert_embeddings', 'model_name')
    op.add_column('alert_iocs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_alert_iocs_tenant_id'), 'alert_iocs', ['tenant_id'], unique=False)
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index('ix_alerts_tenant_detected_at', 'alerts', ['tenant_id', 'detected_at'], unique=False)
    op.create_index('ix_alerts_tenant_severity', 'alerts', ['tenant_id', 'severity'], unique=False)
    op.create_index('ix_alerts_tenant_status', 'alerts', ['tenant_id', 'status'], unique=False)
    op.add_column('audit_log', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.execute("UPDATE cases SET metadata_payload = '{}'::jsonb WHERE metadata_payload IS NULL")
    op.alter_column('cases', 'metadata_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_cases_severity'), table_name='cases')
    op.create_index('ix_cases_tenant_priority', 'cases', ['tenant_id', 'priority'], unique=False)
    op.create_index('ix_cases_tenant_severity', 'cases', ['tenant_id', 'severity'], unique=False)
    op.create_index('ix_cases_tenant_status', 'cases', ['tenant_id', 'status'], unique=False)
    op.add_column('enrichment_jobs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_enrichment_jobs_tenant_id'), 'enrichment_jobs', ['tenant_id'], unique=False)
    op.add_column('enrichment_results', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_enrichment_results_alert_id'), 'enrichment_results', ['alert_id'], unique=False)
    op.create_index(op.f('ix_enrichment_results_job_id'), 'enrichment_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_enrichment_results_provider'), 'enrichment_results', ['provider'], unique=False)
    op.create_index(op.f('ix_enrichment_results_tenant_id'), 'enrichment_results', ['tenant_id'], unique=False)
    op.add_column('ingest_dlq', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_ingest_dlq_correlation_id'), 'ingest_dlq', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ingest_dlq_tenant_id'), 'ingest_dlq', ['tenant_id'], unique=False)
    op.add_column('ingest_failures', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('investigation_events', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('investigation_events', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('investigation_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_investigation_events_alert_created'), table_name='investigation_events')
    op.drop_index(op.f('ix_investigation_events_tenant_alert'), table_name='investigation_events')
    op.drop_index(op.f('ix_investigation_events_tenant_alert_created'), table_name='investigation_events')
    op.create_index(op.f('ix_investigation_events_tenant_id'), 'investigation_events', ['tenant_id'], unique=False)
    op.add_column('normalized_alerts', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_index(op.f('idx_alerts_tenant_last_seen'), table_name='normalized_alerts')
    op.drop_index(op.f('idx_alerts_tenant_severity_last_seen'), table_name='normalized_alerts')
    op.drop_index(op.f('idx_alerts_tenant_status_last_seen'), table_name='normalized_alerts')
    op.drop_index(op.f('ix_normalized_alerts_fingerprint'), table_name='normalized_alerts')
    op.drop_index(op.f('ix_normalized_alerts_lifecycle_state'), table_name='normalized_alerts')
    op.drop_index(op.f('ix_normalized_alerts_raw_event_id'), table_name='normalized_alerts')
    op.drop_index(op.f('ix_normalized_alerts_severity'), table_name='normalized_alerts')
    op.drop_index(op.f('ix_normalized_alerts_tenant_last_seen'), table_name='normalized_alerts')
    op.drop_index(op.f('ix_normalized_alerts_time_bucket'), table_name='normalized_alerts')
    op.drop_index(op.f('normalized_alerts_embedding_hnsw_idx'), table_name='normalized_alerts', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('uq_normalized_alerts_tenant_fingerprint_bucket'), 'normalized_alerts', type_='unique')
    op.drop_constraint(op.f('fk_normalized_alerts_assigned_to'), 'normalized_alerts', type_='foreignkey')
    op.alter_column('pipeline_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('raw_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('idx_raw_events_tenant_received'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_tenant_received'), table_name='raw_events')
    op.execute("UPDATE users SET updated_at = now() WHERE updated_at IS NULL")
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_index(op.f('ix_raw_events_tenant_received'), 'raw_events', ['tenant_id', sa.literal_column('received_at DESC')], unique=False)
    op.create_index(op.f('idx_raw_events_tenant_received'), 'raw_events', ['tenant_id', 'received_at'], unique=False)
    op.drop_column('raw_events', 'updated_at')
    op.alter_column('pipeline_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.create_foreign_key(op.f('fk_normalized_alerts_assigned_to'), 'normalized_alerts', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('uq_normalized_alerts_tenant_fingerprint_bucket'), 'normalized_alerts', ['tenant_id', 'fingerprint', 'time_bucket'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('normalized_alerts_embedding_hnsw_idx'), 'normalized_alerts', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_normalized_alerts_time_bucket'), 'normalized_alerts', ['time_bucket'], unique=False)
    op.create_index(op.f('ix_normalized_alerts_tenant_last_seen'), 'normalized_alerts', ['tenant_id', sa.literal_column('last_seen_at DESC')], unique=False)
    op.create_index(op.f('ix_normalized_alerts_severity'), 'normalized_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_normalized_alerts_raw_event_id'), 'normalized_alerts', ['raw_event_id'], unique=False)
    op.create_index(op.f('ix_normalized_alerts_lifecycle_state'), 'normalized_alerts', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_normalized_alerts_fingerprint'), 'normalized_alerts', ['fingerprint'], unique=False)
    op.create_index(op.f('idx_alerts_tenant_status_last_seen'), 'normalized_alerts', ['tenant_id', 'status', 'last_seen_at'], unique=False)
    op.create_index(op.f('idx_alerts_tenant_severity_last_seen'), 'normalized_alerts', ['tenant_id', 'severity', 'last_seen_at'], unique=False)
    op.create_index(op.f('idx_alerts_tenant_last_seen'), 'normalized_alerts', ['tenant_id', 'last_seen_at'], unique=False)
    op.drop_column('normalized_alerts', 'updated_at')
    op.drop_index(op.f('ix_investigation_events_tenant_id'), table_name='investigation_events')
    op.create_index(op.f('ix_investigation_events_tenant_alert_created'), 'investigation_events', ['tenant_id', 'alert_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigation_events_tenant_alert'), 'investigation_events', ['tenant_id', 'alert_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigation_events_alert_created'), 'investigation_events', ['alert_id', 'created_at'], unique=False)
    op.drop_column('investigation_events', 'updated_at')
    op.drop_column('investigation_events', 'description')
    op.drop_column('investigation_events', 'title')
    op.drop_column('ingest_failures', 'updated_at')
    op.drop_index(op.f('ix_ingest_dlq_tenant_id'), table_name='ingest_dlq')
    op.drop_index(op.f('ix_ingest_dlq_correlation_id'), table_name='ingest_dlq')
    op.drop_column('ingest_dlq', 'updated_at')
    op.drop_index(op.f('ix_enrichment_results_tenant_id'), table_name='enrichment_results')
    op.drop_index(op.f('ix_enrichment_results_provider'), table_name='enrichment_results')
    op.drop_index(op.f('ix_enrichment_results_job_id'), table_name='enrichment_results')
    op.drop_index(op.f('ix_enrichment_results_alert_id'), table_name='enrichment_results')
    op.drop_column('enrichment_results', 'updated_at')
    op.drop_index(op.f('ix_enrichment_jobs_tenant_id'), table_name='enrichment_jobs')
    op.drop_column('enrichment_jobs', 'updated_at')
    op.drop_index('ix_cases_tenant_status', table_name='cases')
    op.drop_index('ix_cases_tenant_severity', table_name='cases')
    op.drop_index('ix_cases_tenant_priority', table_name='cases')
    op.create_index(op.f('ix_cases_severity'), 'cases', ['severity'], unique=False)
    op.alter_column('cases', 'metadata_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('audit_log', 'updated_at')
    op.drop_index('ix_alerts_tenant_status', table_name='alerts')
    op.drop_index('ix_alerts_tenant_severity', table_name='alerts')
    op.drop_index('ix_alerts_tenant_detected_at', table_name='alerts')
    op.alter_column('alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_alert_iocs_tenant_id'), table_name='alert_iocs')
    op.drop_column('alert_iocs', 'updated_at')
    op.add_column('alert_embeddings', sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, server_default=sa.text("''")))
    op.add_column('alert_embeddings', sa.Column('text_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_alert_embeddings_tenant_id'), table_name='alert_embeddings')
    op.drop_index(op.f('ix_alert_embeddings_alert_id'), table_name='alert_embeddings')
    op.create_unique_constraint(op.f('alert_embeddings_alert_id_key'), 'alert_embeddings', ['alert_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
